{% set name = "fortecubeview" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fortecubeview-{{ version }}.tar.gz
  sha256: 35b6633374acb277da0d0224a3a73983c2206eb6901337f82d4f1f6662e5dbc7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pythreejs
    - scikit-image
    - numpy
    - ipywidgets


test:
  imports:
    - fortecubeview
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/evangelistalab/fortecubeview
  summary: A geometry, cube file, and vibrational modes viewer for Psi4 and Forte
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
