context:
  name: fortecubeview
  version: 0.2.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fortecubeview-${{ version }}.tar.gz
  sha256: 35b6633374acb277da0d0224a3a73983c2206eb6901337f82d4f1f6662e5dbc7

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - pythreejs
    - scikit-image
    - numpy
    - ipywidgets

tests:
  - python:
      imports:
        - fortecubeview
      python_version: ${{ python_min }}.*

about:
  summary: A geometry, cube file, and vibrational modes viewer for Psi4 and Forte
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/evangelistalab/fortecubeview

extra:
  recipe-maintainers:
    - hadim
